on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  code_review_job:
    runs-on: ubuntu-latest
    name: ChatGPT Code Review
    steps:
      - name: GenAI Code Review
        uses: zabotinegor/genai-code-review@fix-cmd
        with:
          openai_api_key: ${{ secrets.openai_api_key }}
          github_token: ${{ secrets.GH_PAT }}
          github_pr_id: ${{ github.event.number }}
          openai_model: "gpt-5" # optional
          openai_temperature: 0.5 # optional
          openai_max_tokens: 2048 # optional
          mode: patch # files or patch
          language: en # optional, default is 'en'
          custom_prompt: "" # optional